---
# tasks file for Gunicorn

- name: Upload configuration of gunicorn socket and gunicorn daemon
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'gunicorn.socket.j2', dest: '/etc/systemd/system/gunicorn.socket' }
    - { src: 'gunicorn.service.j2', dest: '/etc/systemd/system/gunicorn.service' } 

- name: Start the gunicorn daemon
  become: yes
  service:
    name: gunicorn.service
    state: started
    enabled: true

