---

- name: Main playbook
  hosts: local_group

  pre_tasks:
    - name: Update cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install dependences
      become: yes
      apt:
        name:
          - python3-pip
          - python3-venv
          - nginx
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - acl
          - python3-psycopg2

    - name: install python libraries in a virtual environment
      pip:
        name:
          - django
          - djangorestframework
          - gunicorn
          - psycopg2-binary
        virtualenv: "{{ venv_dir }}"
        virtualenv_command : python3 -m venv

  roles:
    - Postgresql
    - Django
    - Gunicorn
    - Nginx

